version: '3'
services:
  jira:
    image: cptactionhank/atlassian-jira:latest
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira
      - atlassian-home:/opt/atlassian
  confluence:
    image: cptactionhank/atlassian-confluence:latest
    restart: always
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence
      - atlassian-home:/opt/atlassian
  bitbucket:
    image: atlassian/bitbucket-server:latest
    restart: always
    links:
      - database
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
      - atlassian-home:/opt/atlassian
  database:
    image: postgres:9.6.8
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
      - bitbucket
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  atlassian-home:
  jira-data:
  confluence-data:
  bitbucket-data:
  database-data:
